# Generated by Django 5.0.6 on 2024-07-01 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WebSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MusicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description_filter_html', models.TextField()),
                ('discount_info', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('source_web_promote', models.URLField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('edit_modify_date', models.DateTimeField()),
                ('source_web_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('hit_rate', models.IntegerField()),
                ('show_info', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('locationName', models.CharField(max_length=100)),
                ('on_sales', models.BooleanField()),
                ('price', models.CharField(max_length=255)),
                ('end_time', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.location')),
                ('master_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_unit', to='apps.unit')),
                ('other_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_unit', to='apps.unit')),
                ('show_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_unit', to='apps.unit')),
                ('sub_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_unit', to='apps.unit')),
                ('support_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_unit', to='apps.unit')),
                ('web_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.websales')),
            ],
        ),
    ]
