# Generated by Django 5.0.6 on 2024-07-08 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataModel',
        ),
    ]
